spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jjjshop_single_cloud_git?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

  data:
    redis:
      database: 0
      host: 127.0.0.1
      password: 123456
      port: 6379

# 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
