spring-boot-jjj:
  # 是否启用ansi控制台输出有颜色的字体，dev环境建议开启，服务器环境设置为false
  enable-ansi: false
  # 当前环境服务IP地址/域名
  server-ip: http://127.0.0.1:8893

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jjjshop_single_cloud_git?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  #redis 配置
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password: 123456
